version: "3"
services:
  php:
    build: './php/'
    volumes:
      - ./public:/var/www/html/
    restart: always
    depends_on:
      - mysql

  apache:
    build: './apache/'
    depends_on:
      - php
      - mysql
    ports:
      - "8083:80"
    volumes:
      - ./public:/var/www/html/
    restart: always

  mysql:
    image: mysql:8.0
    platform: linux/x86_64
    restart: always
    volumes:
      - db_data:/var/lib/mysql
      - ./public/dump:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: "rootpassword"
      MYSQL_DATABASE: "restaurant_management"
      MYSQL_USER: "user1"
      MYSQL_PASSWORD: "passwd"
    command: ['mysqld', '--default-authentication-plugin=mysql_native_password']

volumes:
  db_data: